language: node_js
node_js:
  - 8.9.0
cache: yarn
install: yarn 
before_install:
  - yarn global add @angular/cli@latest
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: c951e33f-7b3d-4228-9d58-4bfb880d14cd
  app: webtrekk-customer-management
  branch: master
